

SELECT TABLE_NAME, COLUMN_NAME, CONSTRAINT_NAME, REFERENCED_TABLE_NAME, REFERENCED_COLUMN_NAME
FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE
WHERE REFERENCED_TABLE_NAME = 'producto' AND REFERENCED_COLUMN_NAME = 'id';



SELECT TABLE_NAME, COLUMN_NAME, CONSTRAINT_NAME, REFERENCED_TABLE_NAME, REFERENCED_COLUMN_NAME
FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE
WHERE REFERENCED_TABLE_NAME = 'producto' AND REFERENCED_COLUMN_NAME = 'id';

ALTER TABLE producto MODIFY id VARCHAR(50);
ALTER TABLE canasta_productos MODIFY id_producto VARCHAR(50);
ALTER TABLE colores_producto MODIFY idProducto VARCHAR(50)
ALTER TABLE productousuario MODIFY idProducto VARCHAR(50)

SELECT * FROM producto;
SELECT * FROM colores_producto
SELECT * FROM productocolor
SELECT * FROM productomedidas

ALTER TABLE colores_producto 
ADD CONSTRAINT fk_colores_producto_producto 
FOREIGN KEY (idProducto) REFERENCES producto(id);

ALTER TABLE productousuario 
ADD CONSTRAINT fk_producto_like 
FOREIGN KEY (idProducto) REFERENCES producto(id);

SHOW COLUMNS FROM productocolor;
SHOW COLUMNS FROM productomedidas;

ALTER TABLE productocolor MODIFY idProducto VARCHAR(50)
ALTER TABLE productomedidas MODIFY idProducto VARCHAR(50)